-- Scheduler (Plan C) — isolated `scheduler` schema for the volunteer scheduler.
-- Not exposed via the Data API (only `public` etc. are); reached by Edge Functions
-- via the service role. RLS is enabled as defense in depth. Applied to project
-- twbunmbzyqcqzgffdrib via MCP apply_migration (name: scheduler_schema_init).

create schema if not exists scheduler;

create table if not exists scheduler.ministries (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int not null default 0,
  source text default 'pco',
  created_at timestamptz not null default now()
);

create table if not exists scheduler.roles (
  id bigint generated by default as identity primary key,
  ministry_id bigint not null references scheduler.ministries(id) on delete cascade,
  name text not null,
  needed_count int not null default 1,   -- target people per service
  required boolean not null default true, -- must-fill vs. optional (e.g. Worship Team)
  sort_order int not null default 0,
  unique (ministry_id, name)
);

-- Standalone people directory (imported from Planning Center). Basecamp id is
-- filled in later, only for publish/notify. Free-text volunteers have no source id.
create table if not exists scheduler.people (
  id bigint generated by default as identity primary key,
  pco_id text unique,
  first_name text,
  last_name text,
  nickname text,
  email text,
  bc_person_id bigint,
  source text default 'pco',
  is_free_text boolean not null default false,
  created_at timestamptz not null default now()
);

-- One Sunday service per date.
create table if not exists scheduler.services (
  id bigint generated by default as identity primary key,
  service_date date not null unique,
  title text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  bc_schedule_entry_id bigint,
  created_at timestamptz not null default now()
);

-- One row per slot; a role needing N people yields N slots per service.
create table if not exists scheduler.assignments (
  id bigint generated by default as identity primary key,
  service_id bigint not null references scheduler.services(id) on delete cascade,
  role_id bigint not null references scheduler.roles(id) on delete cascade,
  slot_index int not null default 0,
  person_id bigint references scheduler.people(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  bc_todo_id bigint,
  unique (service_id, role_id, slot_index)
);

alter table scheduler.ministries  enable row level security;
alter table scheduler.roles       enable row level security;
alter table scheduler.people      enable row level security;
alter table scheduler.services    enable row level security;
alter table scheduler.assignments enable row level security;

create index if not exists idx_roles_ministry on scheduler.roles(ministry_id);
create index if not exists idx_services_date  on scheduler.services(service_date);
create index if not exists idx_assign_service on scheduler.assignments(service_id);
create index if not exists idx_assign_person  on scheduler.assignments(person_id);
